[package]
name = "chatbot_backend_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
firestore = "0.43.1"
gcloud-sdk = "0.25.6"
getset = "0.1.3"
itertools = "0.13.0"
thiserror = "1.0.64"
uuid = "1.10.0"
